INSERT INTO campuses (id, name, country, city, initials, email_domain, status) VALUES
  ('kaaf', 'KAAF University College', 'GH', 'Buduburam', 'KA', 'kaaf.edu.gh', 'official'),
  ('ug', 'University of Ghana', 'GH', 'Legon, Accra', 'UG', 'ug.edu.gh', 'official'),
  ('knust', 'Kwame Nkrumah University of Science and Technology', 'GH', 'Kumasi', 'KN', 'knust.edu.gh', 'official'),
  ('ucc', 'University of Cape Coast', 'GH', 'Cape Coast', 'UC', 'ucc.edu.gh', 'official'),
  ('uds', 'University for Development Studies', 'GH', 'Tamale', 'UD', 'uds.edu.gh', 'official'),
  ('uew', 'University of Education, Winneba', 'GH', 'Winneba', 'UE', 'uew.edu.gh', 'official'),
  ('gimpa', 'Ghana Institute of Management and Public Administration', 'GH', 'Accra', 'GI', 'gimpa.edu.gh', 'official'),
  ('ashesi', 'Ashesi University', 'GH', 'Berekuso', 'AS', 'ashesi.edu.gh', 'official'),
  ('unilag', 'University of Lagos', 'NG', 'Lagos', 'UL', 'unilag.edu.ng', 'official'),
  ('ui', 'University of Ibadan', 'NG', 'Ibadan', 'UI', 'ui.edu.ng', 'official'),
  ('oau', 'Obafemi Awolowo University', 'NG', 'Ile-Ife', 'OA', 'oauife.edu.ng', 'official'),
  ('uniben', 'University of Benin', 'NG', 'Benin City', 'UB', 'uniben.edu', 'official'),
  ('unn', 'University of Nigeria, Nsukka', 'NG', 'Nsukka', 'UN', 'unn.edu.ng', 'official'),
  ('abu', 'Ahmadu Bello University', 'NG', 'Zaria', 'AB', 'abu.edu.ng', 'official'),
  ('unilorin', 'University of Ilorin', 'NG', 'Ilorin', 'IL', 'unilorin.edu.ng', 'official'),
  ('unijos', 'University of Jos', 'NG', 'Jos', 'UJ', 'unijos.edu.ng', 'official'),
  ('uniport', 'University of Port Harcourt', 'NG', 'Port Harcourt', 'UP', 'uniport.edu.ng', 'official'),
  ('unical', 'University of Calabar', 'NG', 'Calabar', 'CL', 'unical.edu.ng', 'official'),
  ('unimaid', 'University of Maiduguri', 'NG', 'Maiduguri', 'UM', 'unimaid.edu.ng', 'official'),
  ('noun', 'National Open University of Nigeria', 'NG', 'Abuja', 'NO', 'noun.edu.ng', 'official'),
  ('lasu', 'Lagos State University', 'NG', 'Ojo, Lagos', 'LS', 'lasu.edu.ng', 'official'),
  ('covenant', 'Covenant University', 'NG', 'Ota', 'CU', 'covenantuniversity.edu.ng', 'official'),
  ('babcock', 'Babcock University', 'NG', 'Ilishan-Remo', 'BU', 'babcock.edu.ng', 'official'),
  ('aun', 'American University of Nigeria', 'NG', 'Yola', 'AU', 'aun.edu.ng', 'official'),
  ('futa', 'Federal University of Technology, Akure', 'NG', 'Akure', 'FT', 'futa.edu.ng', 'official'),
  ('futminna', 'Federal University of Technology, Minna', 'NG', 'Minna', 'FM', 'futminna.edu.ng', 'official'),
  ('unizik', 'Nnamdi Azikiwe University', 'NG', 'Awka', 'NA', 'unizik.edu.ng', 'official'),
  ('delsu', 'Delta State University', 'NG', 'Abraka', 'DS', 'delsu.edu.ng', 'official'),
  ('eksu', 'Ekiti State University', 'NG', 'Ado-Ekiti', 'EK', 'eksu.edu.ng', 'official'),
  ('uniosun', 'Osun State University', 'NG', 'Osogbo', 'OS', 'uniosun.edu.ng', 'official')
ON CONFLICT (id) DO NOTHING;
